apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quotegen
  generation: 3
  namespace: pipel
  labels:
    app.kubernetes.io/instance: quotegen
    pipeline.openshift.io/runtime: python
    pipeline.openshift.io/type: openshift
spec:
  params:
    - default: quotegen
      name: APP_NAME
      type: string
  resources:
    - name: image-dfrgpv
      type: image
    - name: git-n1rkjq
      type: git
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: https://github.com/snowjet/demo-quote-gen.git
        - name: revision
          value: master
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(resource.image-dfrgpv)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-python-3
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
      params:
        - name: ARGS
          value:
            - rollout
            - status
            - dc/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: wout
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  selfLink: /apis/tekton.dev/v1beta1/namespaces/pipel/pipelines/quotegen
  resourceVersion: '413840'
  name: quotegen
  uid: b0c23dbe-6022-4210-8231-e3e166255ff2
  creationTimestamp: '2020-09-13T11:08:16Z'
  generation: 9
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:pipeline.openshift.io/runtime': {}
            'f:pipeline.openshift.io/type': {}
        'f:spec':
          .: {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2020-09-13T11:36:04Z'
  namespace: pipel
  labels:
    app.kubernetes.io/instance: quotegen
    pipeline.openshift.io/runtime: python
    pipeline.openshift.io/type: openshift
spec:
  params:
    - default: quotegen
      name: APP_NAME
      type: string
  resources:
    - name: image-quote
      type: image
    - name: git-quote
      type: git
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/snowjet/demo-quote-gen'
        - name: revision
          value: master
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: deploy
      params:
        - name: ARGS
          value:
            - rollout
            - status
            - dc/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: build
      params:
        - name: BUILDER_IMAGE
          value: registry.redhat.io/rhel8/buildah
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'False'
        - name: FORMAT
          value: oci
      resources:
        inputs:
          - name: source
            resource: git-quote
        outputs:
          - name: image
            resource: image-quote
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah-pr-v0-14-3
  workspaces:
    - name: workspace
