---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/snowjet/demo-quote-gen'
  name: quotegen
  labels:
    app: quotegen
    app.kubernetes.io/component: quotegen
    app.kubernetes.io/instance: quotegen
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: quotegen
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: '3.6'
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%

    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - quotegen
        from:
          kind: ImageStreamTag
          name: 'quotegen:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: quotegen
    deploymentconfig: quotegen
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quotegen
        deploymentconfig: quotegen
    spec:
      containers:
        - name: quotegen
          image: ''
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env:
            - name: DATABASE_TYPE
              value: postgresql
            - name: JSON_QUOTE_PATH
              value: "./quotes/quotes.json"
            - name: database-user
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database-user
            - name: database-password
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database-password
            - name: database-name
              valueFrom:
                secretKeyRef:
                  name: database
                  key: database-name          
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler