---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/snowjet/demo-quote-gen'
  name: quotegen
  labels:
    app: quotegen
    app.kubernetes.io/component: quotegen
    app.kubernetes.io/instance: quotegen
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: quotegen
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: '3.6'
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%

    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - quotegen
        from:
          kind: ImageStreamTag
          name: 'quotegen:latest'
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: quotegen
    deploymentconfig: quotegen
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quotegen
        deploymentconfig: quotegen
    spec:
      containers:
        - name: quotegen
          image: ''
          ports:
            - containerPort: 8080
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name          
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
status:
  observedGeneration: 8
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: DockerImage
            name: >-
              image-registry.openshift-image-registry.svc:5000/quote-pipeline/quotegen@sha256:ae1f6a487e3dd6f9bf9c70e06a53f9e81b19d82087e7bee37ed63f198909ac57
  availableReplicas: 1
  unavailableReplicas: 0
  latestVersion: 7
  updatedReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-09-20T08:25:23Z'
      lastTransitionTime: '2020-09-20T08:25:23Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-09-20T23:19:36Z'
      lastTransitionTime: '2020-09-20T23:19:32Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "quotegen-7" successfully rolled out
  replicas: 1
  readyReplicas: 1