---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: database
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: dcaas
    app.kubernetes.io/component: database   
stringData:
  database-name: "$(POSTGRESQL_DATABASE)"
  database-password: "$(POSTGRESQL_PASSWORD)"
  database-user: "$(POSTGRESQL_USER)"