---
kind: Service
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-uri: 'postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="database")].port}'
  name: database
  labels:
    app: database
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: database
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: quotegen
    app.openshift.io/version: 'latest'  
spec:
  ports:
    - name: database
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: database
  sessionAffinity: None