apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  generation: 1
  labels:
    pipeline.openshift.io/runtime: python
    pipeline.openshift.io/type: openshift
  name: quotegen
spec:
  params:
    - default: quotegen
      description: name of DeploymentConfig
      name: DC_NAME
      type: string
  resources:
    - name: app-source
      type: git
    - name: app-image
      type: image
  tasks:
    - name: pytest
      params:
        - name: pythonImage
          value: registry.redhat.io/rhel8/python-38
        - name: ARGS
          value: '-s -v'
        - name: SOURCE_PATH
          value: quotegen
        - name: REQUIREMENTS_FILE
          value: requirements.txt
      runAfter:
        - cache-pypi
      taskRef:
        kind: Task
        name: pytest
      workspaces:
        - name: source
          workspace: workspace
    - name: build
      params:
        - name: BUILDER_IMAGE
          value: registry.redhat.io/rhel8/buildah
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
      resources:
        inputs:
          - name: source
            resource: app-source
        outputs:
          - name: image
            resource: app-image
      runAfter:
        - pytest
        - pytest-postgres
      taskRef:
        kind: ClusterTask
        name: buildah-pr
    - name: deploy
      params:
        - name: ARGS
          value:
            - rollout
            - status
            - dc/$(params.DC_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/snowjet/demo-quote-gen.git'
        - name: revision
          value: master
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: pytest-postgres
      params:
        - name: pythonImage
          value: registry.redhat.io/rhel8/python-38
        - name: ARGS
          value: '--db -s -v'
        - name: SOURCE_PATH
          value: quotegen
        - name: REQUIREMENTS_FILE
          value: requirements.txt
        - name: gitUrl
          value: $(resources.inputs.source.url)
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: quotes
      runAfter:
        - cache-pypi
      taskRef:
        kind: Task
        name: pytest-postgres
      workspaces:
        - name: source
          workspace: workspace
    - name: cache-pypi
      params:
        - name: pythonImage
          value: registry.redhat.io/rhel8/python-38
        - name: SOURCE_PATH
          value: quotegen
        - name: REQUIREMENTS_FILE
          value: requirements.txt
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: cache-pypi
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
